### ISSUE TITLE
Make line animation delays relative to the length of the previous path

### ISSUE THREAD

**Issue by frederickobrien** [frederickobrien/teeline-online#134]
Been meaning to do this for ages. At the moment there's a catch-all one second delay on animating paths in multi-line outlines. A lot of the time this looks ok but occasionally leads to some awkward flows.

As pointed out by @mxdvl, you can measure the precise length for every path using `element.getTotalLength()`. This is demonstrated in [this Svelte playground](https://svelte.dev/repl/b70938d563c443ccaedbb9f3b1feca64?version=4.2.2) and also in the screenshot below for reference.

<img width="1800" alt="image" src="https://github.com/frederickobrien/teeline-online/assets/11380557/0d7b5721-9da0-4445-9bfc-951ba7d3f136">

It would be a nice polish to make the animation delay relative to the length of the preceding dash - and might border on essential if teeline.online were to progress to rendering full sentences or passages.

**Comment by mxdvl** [comment]
👯‍♂️
